### ISSUE TITLE
CodeTidy conflict with Source Control in Studio

### ISSUE THREAD

**Issue by quangmai12** [intersystems/isc-codetidy#20]
I installed codetidy and under Source Control Settings it show pkg.isc.codetidy.extension.Composite is selected.
However this will remove my other Source Control class being used in Studio.
Also by setting this to codetidy, i have pop up error CLASS DOES NOT EXIST> zgetProperty+2^Workbench.SourceControl.Commands
How to fix it?
I did run the command Do ##class(%Studio.SourceControl.Interface).SourceControlClassSet("Workbench.SourceControl.SVN.Studio") which is my source control class but it doesn't help.

**Comment by quangmai12** [comment]
1, yes, i see both existing Source Control and CodeTidy in global.
2. Running the SetExtension method will switch my existing SC as current to CodeTidy > This action removed all sub menu item from my existing SC and added CodeTidy to menu. However, popup errors show if CodeTidy is primary.
3. I was instructed to run this command which brings back existing SC but it also removed CodeTidy from the menu
Do ##class(%Studio.SourceControl.Interface).SourceControlClassSet("Workbench.SourceControl.SVN.Studio")
![CodeTidyError1](https://user-images.githubusercontent.com/47006173/179604711-950464ee-ee4b-4727-97d3-45277f0ba606.png)

**Comment by quangmai12** [comment]
HealthShare 2020.2 [HealthShare Modules: Core:20.1.8624 + Patient Index:20.0.8624] - IRIS for Windows (x86-64) 2020.1 (Build 217_1_20418U) Mon Dec 21 2020 11:42:06 EST

**Comment by quangmai12** [comment]
Nice tool but Fix in #21 may not relate to my issue. I have problem in Studio which cannot have both our Source Control and your Code Tidy  exists in Studio menu at same time. If I set one as primary, the other is removed and via versa.
And get the CLASS DOES NOT EXIST all the time if CodeTidy run in Studio.

**Comment by isc-tleavitt** [comment]
@quangmai12 if installing the latest version from zpm doesn't fix the issue, we can connect over a Teams call or something to debug. If the issue is a behavior of your existing source control extension (Workbench.SourceControl.SVN.Studio) then we can't really help, but if it's an issue in codetidy we might be able to.

**Comment by quangmai12** [comment]
please contact me at qmai@memorialcare.org to set up Team call.

**Comment by isc-tleavitt** [comment]
Root cause for issue was in the other extension (and we figured it out).
