### ISSUE TITLE
Do not insert line breaks inside macros

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems/isc-codetidy#34]
Currently if you have a JSON object inside of an $$$Assert macro in a unit test, e.g.:
```
do $$$AssertEquals({}.%FromJSON(json).prop, value)
```
It will expand to
```
do $$$AssertEquals(
	{
	}.%FromJSON(json).prop, value)
```
This fails to compile because the assert macros do not allow line breaks inside them.

**Comment by isc-tleavitt** [comment]
@isc-egabhart would appreciate if you could take a look at this.

**Comment by isc-tleavitt** [comment]
Note, this is related to #33.
